ARG BASE_IMAGE=ghcr.io/chameleoncloud/l4t-cuda-base:36.4-12.6
FROM ${BASE_IMAGE}

ARG CUDA=12-6
ARG CUDA_VERSION=12.6

RUN apt-get update && apt-get install -y --no-install-recommends \
    cuda-nvcc-${CUDA} cuda-cudart-dev-${CUDA} libcublas-dev-${CUDA} \
    make g++ \
    && rm -rf /var/lib/apt/lists/*

ENV CUDA_HOME=/usr/local/cuda-${CUDA_VERSION}
ENV PATH="${CUDA_HOME}/bin:${PATH}"
